version: 0.2
phases:
  install:
    commands:
      - npm i
      - IS_RELEASE=`git describe --always --tags git@github.com:jwiggins78/ci-test.git | grep -c $CODEBUILD_RESOLVED_SOURCE_VERSION`
      - echo Commit is release commit $IS_RELEASE
  build:
    commands:
      - npm run test
      - "[ $IS_RELEASE = 0 ] && echo 'Need to release and exit' && exit 1"
      - echo Continue to build for deloy... this is a release
