version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.14-browsers
    working_directory: ~/repo
    branches:
      only: 
        - master
    steps:
      - run: echo $CIRCLE_USERNAME caused this run
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test

