version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.14-browsers
    working_directory: ~/repo
    branches:
      only: 
        - master
    steps:
      - run: echo $CIRCLE_USERNAME caused this run
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test
      - run: 
          command: |
            CURRENT_MAJOR_MINOR=`cat package.json | jq -r ".version" | cut -d '.' -f 1,2`
            NEW_MAJOR_MINOR=`date +%y.%-m`
            if [ $CURRENT_MAJOR_MINOR == NEW_MAJOR_MINOR ]; then npm version patch; else npm version $NEW_MAJOR_MINOR.0; fi
            cat package.json

